podTemplate(
  label: 'clickhouse-builder',
  containers: [
    containerTemplate(
      name: 'docker', image: 'docker:19.03', ttyEnabled: true, command: 'cat',
      alwaysPullImage: false,
    ),
    containerTemplate(
      name: 'dind', image: 'gcr.io/s5s-big-hot-k8s/s5s-clickhouse-builder:latest', ttyEnabled: true,
      alwaysPullImage: true,

      privileged: true,
      resourceRequestCpu: "4",
      resourceRequestMemory: "16Gi"
    )
  ],
  volumes: [
    persistentVolumeClaim(mountPath: '/root/.ccache', claimName: 'jenkins-ccache')
  ],
  idleMinutes: 5) {

  node('clickhouse-builder') {
    stage('Checkout') {
      container('jnlp') {
        final scmVars = checkout scm
        echo "scmVars: ${scmVars}"
        env.GIT_COMMIT = scmVars.GIT_COMMIT
        env.GIT_BRANCH = scmVars.GIT_BRANCH 

        withCredentials([string(credentialsId: 'github-keyscan', variable: 'github_keyscan')]) {
          sh """
            [ -d ${env.HOME}/.ssh ] || mkdir -p ${env.HOME}/.ssh
            echo '${github_keyscan}' >> ${env.HOME}/.ssh/known_hosts
          """
        }
        sshagent(['s5-jenkins-bot']) {
          sh "git submodule update --init --recursive"
        }
      }
    }
    stage('Build CH Source') {
      container('dind') {
        sh """
          cd ./docker/packager
          mkdir -p ../s5-server/deb
          ./packager --package-type deb --output-dir ../s5-server/deb --compiler clang-8 --cache ccache --ccache_dir /root/.ccache
        """
      }
    }
    stage('Build CH Image') {
      container('dind') {
        sh """
          cd ./docker/s5-server
          docker build . -t s5s-clickhouse:${GIT_COMMIT}
        """
        // withCredentials([string(credentialsId: 'jenkins-gcp-sa-key', variable: 'JENKINS_GCP_SA_KEY')]) {
        //   sh 'echo ${JENKINS_GCP_SA_KEY} | base64 -d | docker login -u _json_key --password-stdin https://gcr.io'
        // }
        // sh 'docker tag gcr.io/s5s-big-hot-k8s/s5s-clickhouse:${GIT_COMMIT} gcr.io/s5s-big-hot-k8s/s5s-clickhouse:latest'
        // sh 'docker push gcr.io/s5s-big-hot-k8s/s5s-clickhouse:${GIT_COMMIT}'
        // sh 'docker push gcr.io/s5s-big-hot-k8s/s5s-clickhouse:latest'
      }
    }
  }
}